---
abstract: 'Base class and script for filter MARC records.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MARC-Filter
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0
  English: 0
  Getopt::Std: 0
  MARC::File::XML: 0
  Unicode::UTF8: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-MARC-Filter/issues
  homepage: https://github.com/michal-josef-spacek/App-MARC-Filter
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-MARC-Filter
version: '0.01'
